import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import clientsRouter from "./clients.js";
import projectsRouter from "./projects.js";
import projectDemoSeedRouter from "./projectDemoSeed.js";
import resourcesRouter from "./resources.js";
import timesheetsRouter from "./timesheets.js";
import documentsRouter from "./documents.js";
import dashboardRouter from "./dashboard.js";
import uploadsRouter from "./uploads.js";
import capacityRouter from "./capacity.js";
import auditLogsRouter from "./audit-logs.js";
import projectActivityRouter from "./project-activity.js";
import resourceSuggestionsRouter from "./resource-suggestions.js";
import calendarFeedRouter from "./calendar-feed.js";
import biRouter from "./bi.js";
import surveysRouter from "./surveys.js";
import expensesRouter from "./expenses.js";
import tasksRouter from "./tasks.js";
import notificationsRouter from "./notifications.js";
import principalRouter from "./principal.js";
import skillsRouter from "./skills.js";
import businessUnitsRouter from "./business-units.js";
import resourcePlanningRouter from "./resource-planning.js";
import invoicePlanningRouter from "./invoice-planning.js";
import invoicePlanningSeedRouter from "./invoicePlanningSeed.js";
import billingMilestonesRouter from "./billing-milestones.js";
import invoiceSettingsRouter from "./invoice-settings.js";
import reportsRouter from "./reports.js";
import leadsRouter from "./leads.js";
import skillMatrixRouter from "./skill-matrix.js";
import taskTemplatesRouter from "./task-templates.js";
import projectTemplatesRouter from "./project-templates.js";
import closingChecklistRouter from "./closing-checklist.js";
import skillDevelopmentRouter from "./skill-development.js";
import leavesRouter from "./leaves.js";
import topPerformersRouter from "./top-performers.js";
import raidRouter from "./raid.js";
import performanceReviewsRouter from "./performance-reviews.js";
import workstreamsRouter from "./workstreams.js";
import projectReportsRouter from "./project-reports.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(surveysRouter);
router.use(authRouter);
router.use("/calendar", calendarFeedRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(projectsRouter);
router.use(projectDemoSeedRouter);
router.use(resourcesRouter);
router.use(timesheetsRouter);
router.use(documentsRouter);
router.use(dashboardRouter);
router.use(uploadsRouter);
router.use(capacityRouter);
router.use(auditLogsRouter);
router.use(projectActivityRouter);
router.use(resourceSuggestionsRouter);
router.use(biRouter);
router.use(expensesRouter);
router.use(tasksRouter);
router.use(notificationsRouter);
router.use(principalRouter);
router.use(skillsRouter);
router.use(businessUnitsRouter);
router.use(resourcePlanningRouter);
router.use(invoicePlanningRouter);
router.use(invoicePlanningSeedRouter);
router.use(billingMilestonesRouter);
router.use(invoiceSettingsRouter);
router.use(reportsRouter);
router.use(leadsRouter);
router.use(skillMatrixRouter);
router.use(taskTemplatesRouter);
router.use(projectTemplatesRouter);
router.use(closingChecklistRouter);
router.use(skillDevelopmentRouter);
router.use(leavesRouter);
router.use(topPerformersRouter);
router.use(raidRouter);
router.use(performanceReviewsRouter);
router.use(workstreamsRouter);
router.use(projectReportsRouter);

export default router;
