// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/secureprofit-ai/AsistenChat.tsx": () => import("../components/mockups/secureprofit-ai/AsistenChat.tsx"),
  "./components/mockups/secureprofit-ai/DraftLaporan.tsx": () => import("../components/mockups/secureprofit-ai/DraftLaporan.tsx"),
  "./components/mockups/secureprofit-ai/PeringatanPintar.tsx": () => import("../components/mockups/secureprofit-ai/PeringatanPintar.tsx")
};
